# Generated by Django 4.0 on 2021-12-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OriginalURL',
            new_name='URL',
        ),
        migrations.DeleteModel(
            name='ShortURL',
        ),
    ]
