# Generated by Django 4.0 on 2021-12-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0002_rename_originalurl_url_delete_shorturl'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(default=0, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='url',
            name='url',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
