# Generated by Django 4.0 on 2021-12-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_url_shorten_url_url_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='url',
            new_name='og_url',
        ),
    ]
