# Generated by Django 4.0 on 2021-12-16 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0004_rename_url_url_og_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='og_url',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
