# Generated by Django 4.0 on 2021-12-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0005_alter_url_og_url_alter_url_shorten_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='id',
        ),
        migrations.AlterField(
            model_name='url',
            name='og_url',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='url',
            name='shorten_url',
            field=models.CharField(max_length=6),
        ),
    ]
